version: 2
jobs:
   build:
     docker:
       - image: circleci/python:latest
     steps:
       - checkout
       - run: ./test.sh

   deploy:
     docker:
       - image: circleci/python:latest
     steps:
       - run:
           name: Install AWS cli
           command: pip install awscli --upgrade --user
       - run:
           name: Deploy to S3 if tests pass (only on master)
           command: aws s3 sync . s3://circleci.entropyonwheels.com/ --delete


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
