version: 2
jobs:
   build:
     docker:
       - image: circleci/python:latest
     steps:
       - checkout
       - run: ./test.sh

   deploy:
     docker:
       - image: circleci/python:latest
     steps:
       - run:
           name: Install AWS cli
           command: pip install awscli --upgrade --user
       - checkout
       - run:
           name: Deploy to S3 if tests pass (only on master)
           command: ~/.local/bin/aws s3 cp helloworld.html script.js s3://circleci.entropyonwheels.com/


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
